### ISSUE TITLE
[enhancement] Hash not only canvas functions, but also canvas properties

### ISSUE THREAD

**Issue by xem** [Siorki/RegPack#21]
Hi!

Let's explore a new compression idea that I've imagined and successfully implemented with @subzey while making our js1k invitro (https://github.com/subzey/js1k2015invitro)

canvas properties are very verbose.  consider the following snippet:

````
c.globalCompositeOperation = ...;
c.globalAlpha = ...;
c.lineWidth = ...;
c.textAlign = ...;
c.setLineDash = ...;
c.lineDashOffset = ...;
````

But we can hash them too!

Example 1: (without math)

````
// Hash
for(i in c){self[i[0]+i[6]]=i}

// Snippet
c[gC] = ...;
c[gA] = ...;
c[ld] = ...;
c[ti] = ...;
c[se] = ...;
c[ls] = ...;
````

Example 2: (with Math... without polluting the global scope)

````
// Hash
for(i in c){Math[i[0]+i[6]]=i}

with(Math){

// Snippet
c[gC] = ...;
c[gA] = ...;
c[ld] = ...;
c[ti] = ...;
c[se] = ...;
c[ls] = ...;

}
````

This is just an explanation of the idea. It deserves a proper implementation...

Cheers

**Comment by Siorki** [comment]
I finally figured out how it works, it is a bit more subtle than renaming the methods.
The usual method hashing `c[hash]=c[i]` does not work on properties, because it copies the current value of the property, not a reference. The internal clockwork will still access `c.fillStyle` which will have kept its initial value even though you set `c.fy` in the meantime.

Your approach stores the names, not the references, so it will work on both properties and methods, however it requires a second level of indirection upon use. You work around that using either globals (example 1) or another object (example 2).

I wonder if we could not directly use c itself for that purpose. Building on your examples, the hashing loop would be limited to `c[i[0]+[i[6]]=i`, and then used by `c[c.gC]= ...; c[c.fc](...);`. The packer would promptly reduce the string `c[c.` to a single byte so no use of `with()` would even be necessary.

I shall tinker a bit with that before bringing it into production. Thanks for the great idea !

**Comment by xem** [comment]
Thanks for liking and enhancing the original idea.
I guess there's no problem in storing hashes in c as well.
The question is: can we find a hash that is precise enough to differentiate all the methods and all the properties of canvas? c[0]+c[6] may not be enough and could make different things overlap.
@subzey worked on an implementation, I'll ask him to explain us which hash he used.
Cheers!

**Comment by subzey** [comment]
If you need any additial info, here's the stuff invitro was built with: https://github.com/subzey/js1k2015invitro/blob/master/make.js#L186-L190

**Comment by Siorki** [comment]
I opened issue #23 to discuss hashing functions. 
For the record, `c[0]+[c[6]]` is commonly seen for 2D contexts yet there may be better options depending on the methods used inside the code.
 I took notice of the one you are using in the invitro `c[0]+[c[3]||0]+[c[6]]+[c[9]]`, quite long indeed but discriminates precisely between the multiple methods and properties.

**Comment by subzey** [comment]
There's a tool for that, too, https://github.com/subzey/js1k2015invitro/blob/master/tools/hashstat.html
(I was too lazy to embed it into build.js)

**Comment by xem** [comment]
Hey, I just realize that you're working on this feature! great! Cheers

**Comment by Siorki** [comment]
Ongoing work is performed in the branch v4_dev.
I'll merge that into master once all features are v4.0 are complete and the version is thoroughly tested.

**Comment by Siorki** [comment]
Property hashing perfomed in parallel with method hashing (a description in the wiki will be needed to explain the workflow), then both are independently fed to the packer. Only the best result is kept.
Applied to both 2D and WebGL context.

Work completed in branch and merged to master.

**Comment by subzey** [comment]
Awesome!
