### ISSUE TITLE
Make that NPM modules :)

### ISSUE THREAD

**Issue by gre** [Siorki/RegPack#6]
I would love to make your awesome tools some NPM modules. Actually I recently created "jscrush" https://npmjs.org/package/jscrush that you can both use from the CLI or from NodeJS / Browserify. 
I'm using it like this: https://gist.github.com/gre/9504494#file-package-json

**Are you thinking of spliting your tools into NPM modules? Do you want me to do it?**

PS: Is your tool free software? Can you add any license in the README?

Thanks a lot

**Comment by kanaka** [comment]
https://github.com/Siorki/RegPack/pull/14

Moves the main source code for RegPack to regPack.js. The web page loads regPack.js and should still work the same as before.

The regPack.js source can be used directly with node.js:
```
npm install   # to install minimist module for command line parsing
node ./regPack.js input.js --crushGainFactor 1 --crushLengthFactor 0 --crushCopiesFactor 0 > output.js
```

Alos, have you heard back from Aivo about the license of JsCrush so that RegPack can get a license too?

**Comment by Siorki** [comment]
#14 merged into main after successfully running tests. Many thanks for the refactor !
README updated to feature the command line above.

AFAIK Aivo has no plans for a license. I will replace the borrowed code in the next major revision (see issue #7) to deal with that.

**Comment by kanaka** [comment]
@Siorki Sounds good.

BTW, regarding licenses, if you decide to use a copyleft license to prevent closed source derivatives, I might suggest the MPL 2.0 which is better suited to dynamic non-compiled code such as JavaScript than the GPL variants. In either case, you may want to clarify in the your license that the unpacker code that is generated as part of the compressed source does not taint the generated code. I.e. that it does not affect how people are allowed to license code that the run RegPack over.

It's sort of a unusual space when code with one license transforms code under a different license especially when it includes new code in the result. So you just might want to clarify so that people are certain that they have the freedom to regpack their code without concern.

Anyways, thanks for the great project. It will allow me to pack in quite a bit more functionality for my JS1K submission :-)

**Comment by aivopaas** [comment]
I just sticked a MIT license on JSCrush.

**Comment by kanaka** [comment]
@aivopaas thanks!

**Comment by Siorki** [comment]
Thanks Aivo, I followed suit with the MIT license.
I do not see a business environment using RegPack for compression, nor a closed-source derivative thereof, as they have better options (server-side zip, for instance). No need to prevent that IMHO.
