### ISSUE TITLE
Nested backticks in template literal causes string renaming module to miss occurrences

### ISSUE THREAD

**Issue by xem** [Siorki/RegPack#82]
Hello!

I tried to pack this snippet:

```
for(b.innerHTML=`<div style=transform-style:preserve-3d;position:fixed;perspective:80vh;margin:40vh+50vw><div style=transform-style:preserve-3d;position:fixed;transform:translateX(-30vh)translateZ(-30vh)rotateX(55deg)rotateZ(28deg><div id=s style=transform-style:preserve-3d;position:fixed;width:72vh;height:48vh;background:#19c;animation:a+9s><style>@keyframes a{50%{transform:rotateZ(-50deg`,m=`055000000000000552000500067760005012210500066660005012210555558855555012210000000000000012210000004400000012211111111111113112222211111122220222222211222222100000222211222222100000222211111222000000222211111222000000`,i=12;i--;)for(j=18;j--;)+m[18*i+j]&&(s.innerHTML+=`<div style=transform-style:preserve-3d;position:fixed;transform:translateY(${i*4+(m[i*18+j]==4?-15:0)}vh)translateX(${j*4}vh)translateZ(${[1,1,1,2,1,1,1,1,13][m[i*18+j]]}vh)scaleX(1.1)scaleY(${m[i*18+j]==4?5:1.1})scaleZ(${[,.5,.8,.2,.2,5,8,11,2][m[i*18+j]]}><p style=transform-style:preserve-3d;position:fixed;width:4vh;height:4vh;background:#${[`349`,`ed7`,`0a0`,`da4`][m[i*18+j]]||`ddd`};transform:translateZ(4vh><p style=transform-style:preserve-3d;position:fixed;width:4vh;height:4vh;background:#${[,`ed7`,`0a0`,`da4`][m[i*18+j]]||`ddd`};transform:rotateY(90deg)translate(-2vh)translateZ(-2vh><p style=transform-style:preserve-3d;position:fixed;width:4vh;height:4vh;background:#${[,`ed7`,`0a0`,`da4`][m[i*18+j]]||`ddd`};transform:rotateY(90deg)translate(-2vh)translateZ(2vh><p style=transform-style:preserve-3d;position:fixed;width:4vh;height:4vh;background:#${[,`fe8`,`0c0`,`da4`][m[i*18+j]]||`edd`};transform:rotateX(90deg)translateY(2vh)translateZ(-2vh>`);for(i=7;i--;)s.innerHTML+=`<div style=transform-style:preserve-3d;position:fixed;transform:translateX(${[10,26,31,2,59,54,10][i]}vh)translateY(${[-11,-6,2,-5,-5,14,14][i]}vh)translateZ(${[20.9,33,45,21,21,21,21][i]}vh)scaleX(${[2.5,1,.5,.5,.5,.3,.3][i]})scaleY(${[1.5,1,.5,.5,.5,.3,.3][i]})scaleZ(.5><p style=transform-style:preserve-3d;position:fixed;width:20vmin;height:20vmin;background:#b31;clip-path:polygon(50%+0,0+99%,99%+99%);transform:translateZ(9vmin)translateY(4.9vmin)rotateX(-60deg><p style=transform-style:preserve-3d;width:20vmin;height:20vmin;position:fixed;background:#b31;clip-path:polygon(50%+0,0+99%,99%+99%);transform:translateZ(9vh)translateX(-4.9vh)rotateY(-60deg)rotateZ(90deg><p style=transform-style:preserve-3d;width:20vmin;height:20vmin;position:fixed;background:#a31;clip-path:polygon(50%+0,0+99%,99%+99%);transform:translateZ(9vh)translateX(4.9vh)rotateY(60deg)rotateZ(-90deg>
```

the output was 995b.

Then I prevented the vars i and j to be reassigned, and the output fell to 987b.

Could RegPack avoid reassigning vars if it's bad?

**Comment by Siorki** [comment]
I get slightly different values (997 and 989) but the same interesting result that replacing `j` with `L`  increases the output by 8 bytes.

There is no check against variable renaming doing that, simply because it is not supposed to happen. Variable renaming is expected to operate at constant length, only providing an extra token - and thus an extra compression round - for the packer.

In your example, the code performing the replacement seems to mess around. Even after replacements there are copies of `j` remaining in the code, and the difference in size comes from the packer compressing the string `m[i*18+j]` in one case, whereas the same token gets assigned to `m[i*18+` after the incomplete replacement is performed. I shall follow up on that.


On a side note : is your syntax `${expression}` CSS standard or does it come from some framework ? If it is the former, I'll file another bug as the `$` is recognized as a variable - which it isn't.

**Comment by xem** [comment]
Hi, thanks for your answer!

No, ${expression} is not part of CSS standard: my CSS code is generated by a template literal, the ${exression} occurrences you see are those of my template literal 

Ex:

```
s.innerHTML+=`<div style="left:${i*20}vh;">
```

Cheers!

**Comment by Siorki** [comment]
Oops ... I had CSS in mind while trying to read it, of course it is a template literal. Thus another issue => #84 

There is a peculiar construct in the code which RegPack chokes on. Namely, you are using backticks inside a template literal (I had no idea this would work, had to test it separately), and RegPack mistakenly believes the string ends after the first backtick.

```javascript
var j = `world`;
var k = `${`hello `+j}`;
// RegPack reads that as two strings `${` and `+j}`
```

Short-term solution : modify `ShapeShifter::identifyStrings()` to avoid closing strings in the middle of a template literal

Long-term solution : use a real parser

**Comment by Siorki** [comment]
Once the string boundaries are correctly computed, another issue comes up.

Upon building the output, RegPack now escapes the backticks inside the string (since they are the same characters as the string delimiters), however as you demonstrated, this is not necessary inside a template literal. (Plus, it obscures issue #83)

**Comment by Siorki** [comment]
Escaping fixed too. Now, preventing `j` from being renamed costs 1 byte.

https://github.com/Siorki/RegPack/commit/867383465b5186fdd16f1509af78d9233d6c6006
https://github.com/Siorki/RegPack/commit/7707011db716376b947c4a6e26e0bbef1bc47a70
