### ISSUE TITLE
Don't use "\" as a token if avoiding it makes the output smaller

### ISSUE THREAD

**Issue by xem** [Siorki/RegPack#83]
Hello again!

I tried to compress the following snippet:

```
for(b.innerHTML=`<div style=transform-style:preserve-3d;position:fixed;perspective:80vh;margin:40vh+50vw><div style=transform-style:preserve-3d;position:fixed;transform:translateX(-30vh)translateZ(-30vh)rotateX(55deg)rotateZ(28deg><div id=s style=transform-style:preserve-3d;position:fixed;width:72vh;height:48vh;background:#19c;animation:a+9s><style>@keyframes a{50%{transform:rotateZ(-50deg`,m=`055000000000000552000500067760005012210500066660005012210555558855555012210000000000000012210000004400000012211111111111113112222211111122220222222211222222100000222211222222100000222211111222000000222211111222000000`,i=12;i--;)for(j=18;j--;)+m[18*i+j]&&(s.innerHTML+=`<div style=transform-style:preserve-3d;position:fixed;transform:translateY(${i*4+(m[i*18+j]==4?-15:0)}vh)translateX(${j*4}vh)translateZ(${[1,1,1,2,1,1,1,1,13][m[i*18+j]]}vh)scaleX(1.1)scaleY(${m[i*18+j]==4?5:1.1})scaleZ(${[,.5,.8,.2,.2,5,8,11,2][m[i*18+j]]}><p style=transform-style:preserve-3d;position:fixed;width:4vh;height:4vh;background:#${[`349`,`ed7`,`0a0`,`da4`][m[i*18+j]]||`ddd`};transform:translateZ(4vh><p style=transform-style:preserve-3d;position:fixed;width:4vh;height:4vh;background:#${[,`ed7`,`0a0`,`da4`][m[i*18+j]]||`ddd`};transform:rotateY(90deg)translate(-2vh)translateZ(-2vh><p style=transform-style:preserve-3d;position:fixed;width:4vh;height:4vh;background:#${[,`ed7`,`0a0`,`da4`][m[i*18+j]]||`ddd`};transform:rotateY(90deg)translate(-2vh)translateZ(2vh><p style=transform-style:preserve-3d;position:fixed;width:4vh;height:4vh;background:#${[,`fe8`,`0c0`,`da4`][m[i*18+j]]||`edd`};transform:rotateX(90deg)translateY(2vh)translateZ(-2vh>`);for(i=7;i--;)s.innerHTML+=`<div style=transform-style:preserve-3d;position:fixed;transform:translateX(${[10,26,31,2,59,54,10][i]}vh)translateY(${[-11,-6,2,-5,-5,14,14][i]}vh)translateZ(${[20.9,33,45,21,21,21,21][i]}vh)scaleX(${[2.5,1,.5,.5,.5,.3,.3][i]})scaleY(${[1.5,1,.5,.5,.5,.3,.3][i]})scaleZ(.5><p style=transform-style:preserve-3d;position:fixed;width:20vmin;height:20vmin;background:#b31;clip-path:polygon(50%+0,0+99%,99%+99%);transform:translateZ(9vmin)translateY(4.9vmin)rotateX(-60deg><p style=transform-style:preserve-3d;width:20vmin;height:20vmin;position:fixed;background:#b31;clip-path:polygon(50%+0,0+99%,99%+99%);transform:translateZ(9vh)translateX(-4.9vh)rotateY(-60deg)rotateZ(90deg><p style=transform-style:preserve-3d;width:20vmin;height:20vmin;position:fixed;background:#a31;clip-path:polygon(50%+0,0+99%,99%+99%);transform:translateZ(9vh)translateX(4.9vh)rotateY(60deg)rotateZ(-90deg>`
```

RegPack used "\\\\" ("\\" escaped) as a token, but if it hadn't used it, the output would have been lignter (984b)

Could you avoid using this char as a token when it's not efficient?

Thanks!

**Comment by Siorki** [comment]
Linked with #47 which introduced escaped characters as tokens, for the packer phase only (not the crusher).

First check to perform - is the gain reassessed with the actual cost of 2 bytes ?

**Comment by Siorki** [comment]
The byte size of the token is currently not taken into account when computing gain.

I considered skipping `\` if the gain for it is negative, then reinjecting it for the next match, but this is unnecessary.
However, it turns out that tokens costing 2 bytes (`\` or Unicode 128-2047) should only be considered after the 1-byte ones are exhausted. The rationale is that a 2-byte token can always be replaced by a 1-byte token - if there is any left - while shortening the output.
_Proof : the 1-byte token can add 1 byte to the character class in the regex. The packed string contains the token exactly once in the dictionary (list of tokens & matched strings), and at least twice in replacements (with less than two occurences, a string is not packed). So a gain of at least 2 bytes._

Consequence : the packer should use all 1-byte tokens first. Then, if more are needed, it should include `\`, and compute the gain with the actual token length. All strings with negative gain can be immediately dropped (gain cannot improve with a shorter token as there are none left).

**Comment by Siorki** [comment]
Very difficult issue to tackle properly.
All non-reg tests for #47 break one after the other.
Good thing to have them, they make sure all edge cases are handled properly. I had to change the expected result for one of the cases though, discarding `\` as a candidate token yielded a result 4 bytes shorter.

**Comment by Siorki** [comment]
Issue fixed, provided sample now down to 984b packed.

https://github.com/Siorki/RegPack/commit/386c05eed6ac527bcde1a19512174873e166cd30
